version = 1

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Ganeshvarikuppala/argo-cd"
  dependencies_vendored = true